spring:
  application:
    name: SpringBootSOAP2
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdb
    username: postgres
    password: tiger
    driver-class-name: org.postgresql.Driver
    hikari:
     connection-timeout: 5000
     maximum-pool-size: 5
  jpa:
    show-sql: true
    properties:
      hibernate:
       format-sql: true
       dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
 level:
  org:
   hibernate:
    type:
     descriptor:
      sql: TRACE
    SQL: debug